---
- hosts: node1
  tasks:
     - name: resourcemanager container
       docker_container:
          name: resourcemanager
          image: elek/hadoop-yarn-resourcemanager
          state: started
          network_mode: host
          volumes: "/grid/0/:/data"
          pull: true 
          env:
             CORE_SITE_fs_default_name: "hdfs://{{gateway}}:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "{{gateway}}:9000"
             HDFS_SITE_dfs_namenode_name_dir: /data/namenode
             YARN_SITE_yarn.resourcemanager.hostname: "{{gateway}}"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: false
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: false
- hosts: all
  tasks:
     - name: nodemanager container
       docker_container:
          name: nodemanager
          image: elek/hadoop-yarn-nodemanager
          state: started
          network_mode: host
          volumes: "/grid/0/:/data"
          pull: true 
          env:
             CORE_SITE_fs_default_name: "hdfs://{{gateway}}:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "{{gateway}}:9000"
             HDFS_SITE_dfs_datanode_data_dir: /data/datanode
             YARN_SITE_yarn.resourcemanager.hostname: "{{gateway}}"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: false
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: false
             YARN_SITE_yarn.nodemanager.delete.debug-delay-sec: 600
