version: "2"
services:
   resourcemanager:
      image: elek/hadoop-yarn-resourcemanager
      container_name: yarn_resourcemanager
      ports: 
         - 8088:8088
   nodemanager:
      image: elek/hadoop-yarn-nodemanager
      links:
         - resourcemanager
networks:
   default:
      external:
         name: hadoop
