version: "2"
services:
   zookeeper:
      image: elek/zookeeper
      container_name: zookeeper
   master:
      image: elek/hbase-master
      hostname: master
      volumes:
         - ./regionserver:/opt/hbase/conf/regionservers
#   regionserver1:
   regionserver:
#      environment:
#         - HBASE_SITE_hbase_regionserver_hostname=regionserver1
#      container_name: regionserver1
      image: elek/hbase-regionserver
#      hostname: regionserver1
networks:
   default:
      external:
         name: hadoop
