version: "2"
services:
   namenode:
      image: elek/hadoop-hdfs-namenode
      container_name: hdfs_namenode
      ports: 
         - 50070:50070
      networks:
         hadoop:
            aliases:
               - hdfs-namenode.domain
   datanode:
      image: elek/hadoop-hdfs-datanode
      networks:
         - hadoop
networks:
   hadoop:
      external: true
